resolver: lts-20.11 # GHC 9.2.5
# lts-20.11 # GHC 9.2.5
# lts-18.28 # GHC 8.10.7

extra-deps: [colourista-0.1.0.2]
# removed base-noprelude-4.13.0.0
# removed tasty-html-0.4.1.2

ghc-options:
  "$locals": -fhide-source-paths

