#!/bin/sh

# téléchargemnt binaire
cd bin
wget -q https://github.com/pascalpoizat/fbpmn/releases/download/v0.3.7/fbpmn-0.3.7-linux.x86_64.zip
unzip fbpmn-0.3.7-linux.x86_64.zip
cd ..

# git clone FBPMN
git clone https://github.com/pascalpoizat/fbpmn.git

# téléchargement tlatools.jar
wget https://github.com/tlaplus/tlaplus/releases/download/v1.6.0/tla2tools.jar

# TODO installer pwsh