openapi: 3.0.2
info:
  description: This is a simple API
  version: 1.0.0-oas3
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /version:
    get:
      summary: Get the current fbpmn version
      description: ''
      operationId: fbpmn version
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
  /verifs:
    get:
      summary: list all the verifications of BPMN model
      description: ''
      operationId: getVerifications
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Verification'
    post:
      summary: Add a new verification
      description: Add a new verification
      operationId: addVerification
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Verification'
        '405':
          description: Invalid input
          
  '/verifs/{verifId}':
    get:
      summary: searches verification of BPMN model
      description: Returns a single verification
      operationId: getVerification
      parameters:
        - name: verifId
          in: path
          description: ID of verification to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Verification'
        '400':
          description: Invalid ID supplied
        '404':
          description: Verification not found
components:
  schemas:
    Version:
      properties:
        num:
          type: integer
          format: int64
          example: 0.3.6
      xml:
        name: version
      type: object
    Verification:
      type: object
      properties:
        id: 
          type: integer
          format: int64
          example: 2
        ref:
          type: string
          example: /verifs/:id/
        resultat:
          type: array
          items:
            $ref: '#/components/schemas/Verif'
    Verif:
      properties:
        mode:
          type: string
          description: Communication mode
          enum:
            - TYPE
            - SAFE
            - SOUND
            - MSGSOUND
          example: TYPE
        prop:
          type: string
          description: Propertie
          enum:
            - BAG
            - FIFOPAIR
            - CAUSAL
            - INBOX
            - OUTBOX
            - FIFO
            - RSC
          example: BAG
        value:
          type: boolean
          example: true
      xml:
        name: verif
      type: object

host: virtserver.swaggerhub.com
basePath: /TEAM5449/fBPMN/1.0.0
schemes:
  - https