openapi: 3.0.2
info:
  description: This is a simple API
  version: 1.0.0-oas3
  title: Simple Inventory API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: verification
    description: Resources about verification
paths:
  /version:
    get:
      tags: 
        - verification
      summary: Get the current fbpmn version
      description: ''
      operationId: fbpmn version
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
  /verifs:
    get:
      tags: 
        - verification
      summary: List all the verifications of BPMN model
      description: ''
      operationId: getVerifications
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Verification'
    post:
      tags: 
        - verification
      summary: Add a new verification
      description: Add a new verification
      operationId: addVerification
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Verification'
        '405':
          description: Invalid input
          
  '/verifs/{verifId}':
    get:
      tags: 
        - verification
      summary: Searches verification of BPMN model
      description: Returns a single verification
      operationId: getVerification
      parameters:
        - name: verifId
          in: path
          description: ID of verification to return
          required: true
          schema:
            type: integer
            format: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Verification'
        '400':
          description: Invalid ID supplied
        '404':
          description: Verification not found
components:
  schemas:
    Version:
      properties:
        num:
          type: integer
          format: integer
          example: 0.3.6
      xml:
        name: version
      type: object
    Verification:
      properties:
        id: 
          type: integer
          format: integer
          example: 2
        ref:
          type: string
          example: /verifs/:id/
        file: 
          type: string
          example: /verifs/:id/diagram.bpmn
        resultat:
          $ref: '#/components/schemas/Result'
      xml:
        name: verification
      type: object
    Result:
      properties:
        model: 
          $ref: '#/components/schemas/Network'
    Network: 
      properties:
        BAG:
          $ref: '#/components/schemas/Property'
        FIFOPAIR:
          $ref: '#/components/schemas/Property'
        CAUSAL:
          $ref: '#/components/schemas/Property'
        INBOX:
          $ref: '#/components/schemas/Property'
        OUTBOX:
          $ref: '#/components/schemas/Property'
        FIFO:
          $ref: '#/components/schemas/Property'
        RSC:
          $ref: '#/components/schemas/Property'
      xml:
        name: network
      type: object
    Property:
      properties:
        TYPE: 
          $ref: '#/components/schemas/Stat'
        SAFE:
          $ref: '#/components/schemas/Stat'
        SOUND:
          $ref: '#/components/schemas/Stat'
        MSGSOUND:
          $ref: '#/components/schemas/Stat'
      xml:
        name: Property
      type: object
    Stat:
      properties:
        trans: 
          type: integer
          format: integer
          example: 64
        depth: 
          type: integer
          format: integer
          example: 128
        states: 
          type: integer
          format: integer
          example: 31
        value:
          type: boolean
          example: true
      xml:
        name: Stat
      type: object

host: virtserver.swaggerhub.com
basePath: /TEAM5449/fBPMN/1.0.0
schemes:
  - https