version: "3"

services:
  api:
    build:
      context: ./backend
    image: fbpmn-api
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  client:
    build:
      context: ./frontend
    image: fbpmn-client
    depends_on:
      - api
    ports:
      - "3000:80"

  db:
    container_name: fbpmn-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: fBPMN_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: ""
    ports:
      - "33061:3306"
