version: "3"

services:
  api:
    build:
      context: ./backend
    image: fbpmn-api
  client:
    build:
      context: ./frontend
    image: fbpmn-client
    depends_on:
      - api
    ports:
      - "3000:80"
